?start : trees
trees : tree+
tree : node
| cons
| leaf

node : "node" "(" (operator) (cons|leaf|node) ")"
operator : "+"|"-"|"*"|"/"|"="

cons : "cons" "(" (node|leaf) (node|leaf) ")"

leaf : "leaf" "(" (variable|constant|type) (identifier|number) ")"
variable : "ID"
constant : "INTEGER"|"REAL"|"ID"
type : "INT"|"FLOAT"
identifier : /[a-zA-Z_][a-zA-Z0-9_]*/
number : /[0-9]*([0-9]|.[0-9]+)/

%import common.WS
%ignore WS
