?start : trees
trees : tree+
tree : node
| leaf

node : "node" "(" operator cons ")" -> operation
| "node" "(" assign cons ")" -> assignment

assign = "="
operator : "+"|"-"|"*"|"/"

cons : "cons" "(" (node|leaf) (node|leaf) ")"

leaf : "leaf" "(" (variable|constant) (identifier|number) ")"
variable : "ID"
constant : "INTEGER"|"REAL"
identifier : /[^\t \n\r~|\(\)\+\-]+/
number : /[0-9]*([0-9]|.[0-9]+)/

%import common.WS
%ignore WS
