Program ::= Statements

Statements ::= StatementNewline
|Statements StatementNewline

StatementNewline ::= Statement
| Newlines Statement

Statement ::= Assign Newlines
| Method Newlines

Assign ::= Variable TILDE VERTICAL Expression VERTICAL

Method ::= Print

Print ::= PRINT "(" Expression ")"

Expression ::= Expression "+" Term
| Expression "-" Term
|Term

Term::=Factor

Factor::=Variable
|Constant
|"(" Expression ")"

Variable ::= ID
Constant::= INTEGER | FLOAT | STRINGS

Newlines::=NEWLINE
|Newlines NEWLINE

PRINT ::= "📝"
TILDE ::= "~"
VERTICAL ::= "|"
OPERATOR ::= "+"|"-"
INTEGER ::= [0-9]+
STRINGS::= "'" ([^']|"\'")* "'"
FLOAT ::= [0-9]+ "." [0-9]+
NEWLINE ::= "\r" | "\r\n" | "\n"
ID ::= [^\t \n\r~|()+-]+
