Program ::= Statements

Statements ::= StatementNewline
|Statements StatementNewline

StatementNewline ::= Statement
| Newline Statement
| StatementNewline Statement

Statement ::= Assign Newline

Assign ::= Variable TILDE VERTICAL Expression VERTICAL

Expression ::= Expression OPERATOR Term

Term::=Factor

Factor::=Variable
|Constant
|"(" Expression ")"

Variable ::= ID
Constant::= INTEGER | FLOAT

Newline::=NEWLINE
|Newline NEWLINE

SEMICOLON ::= ";"
TILDE ::= "~"
VERTICAL ::= "|"
OPERATOR ::= "+"|"-"
INTEGER ::= [0-9]+
FLOAT ::= [0-9]+ "." [0-9]+
NEWLINE ::= "\r" | "\r\n" | "\n"
ID ::= .*
