Program ::= Statements

Statements ::= StatementNewline
|Statements StatementNewline

StatementNewline ::= Statement
| Newlines Statement
| StatementNewline Statement

Statement ::= Assign Newlines

Assign ::= Variable TILDE VERTICAL Expression VERTICAL

Expression ::= Expression OPERATOR Term

Term::=Factor

Factor::=Variable
|Constant
|"(" Expression ")"

Variable ::= ID
Constant::= INTEGER | FLOAT

Newlines::=NEWLINE
|Newlines NEWLINE

TILDE ::= "~"
VERTICAL ::= "|"
OPERATOR ::= "+"|"-"
INTEGER ::= [0-9]+
FLOAT ::= [0-9]+ "." [0-9]+
NEWLINE ::= "\r" | "\r\n" | "\n"
ID ::= [^\t \n\r~|()+-]+
